/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_packtpub_e4_advanced_c_Maths */

#ifndef _Included_com_packtpub_e4_advanced_c_Maths
#define _Included_com_packtpub_e4_advanced_c_Maths
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_packtpub_e4_advanced_c_Maths
 * Method:    nativeAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_packtpub_e4_advanced_c_Maths_nativeAdd
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
